/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  LineFollower_v1_0                              */
/*      FILE         :  idcode.c                                       */
/*      DESCRIPTION  :  Flash ROM protection configuration             */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  Other                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/                                                                         
                                                                           
                                                                           
                                                                           
                                                                          


 #pragma address id_code = 0xFFFFFFA0

 typedef unsigned int uint32_t;

 const uint32_t id_code[4] = {
         0xFFFFFFFF,
         0xFFFFFFFF,
         0xFFFFFFFF,
         0xFFFFFFFF,
 };

