/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  LineFollower_v1_0                              */
/*      FILE         :  interrupt_handlers.c                           */
/*      DESCRIPTION  :  Interrupt program                              */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  Other                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/                                                        
                                                                         

#include <machine.h>
#include "vect.h"
#pragma section IntPRG

// Exception(Supervisor Instruction)
void Excep_SuperVisorInst(void){/* brk(); */}

// Exception(Undefined Instruction)
void Excep_UndefinedInst(void){/* brk(); */}

// Exception(Floating Point)
void Excep_FloatingPoint(void){/* brk(); */}

// NMI
void NonMaskableInterrupt(void){/* brk(); */}

// Dummy
void Dummy(void){/* brk(); */}

// BRK
void Excep_BRK(void){ wait(); }

