/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  LineFollower_v1_0                              */
/*      FILE         :  sbrk.h                                         */
/*      DESCRIPTION  :  Header file of sbrk file                       */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  Other                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x400