/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  LineFollower_v1_0                              */
/*      FILE         :  stacksct.h                                     */
/*      DESCRIPTION  :  Setting of Stack area                          */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  Other                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/
#pragma stacksize su=0x100
#pragma stacksize si=0x300